[package]
name = "picviewer"
version = "0.0.1"
description = "A private local image browser"
edition = "2021"
license = "MIT"
repository = "https://github.com/Lethita/PicViewer"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
