const IMAGE_TYPES = new Set(['jpg','jpeg','png','gif','webp','bmp','avif','svg']);
const BATCH_SIZE = 20;
const THUMBNAIL_WIDTH = 720;
const THUMBNAIL_CONCURRENCY = 3;
const CACHE_LIMIT = 400;
const messages={zh:{title:'PicViewer · 本地图片浏览',defaultGallery:'默认图库',newGallery:'新建图库',addDirectory:'添加目录',images:'图片',refresh:'刷新索引',manage:'管理目录',sources:'图片来源',directories:'关联目录',addAnother:'+ 添加另一个目录',permissionTip:'浏览器重新打开后，可能需要你再次授权目录访问。',drop:'放开以添加目录',privacy:'图片仍只保存在你的设备上',empty:'还没有关联图片目录',reconnect:'需要重新连接当前图库的目录',select:'选择目录',reconnectButton:'重新连接目录',needReconnect:'目录需要重新连接',none:'尚未添加图片',imageCount:(d,i)=>`${d} 个目录 · ${i} 张图片`,permission:'需要重新授权',photoCount:n=>`${n} 张图片`,reconnectShort:'重新连接',emptyDirectories:'还没有关联任何目录。'},en:{title:'PicViewer · Local Image Browser',defaultGallery:'Default Gallery',newGallery:'New Gallery',addDirectory:'Add folder',images:'Images',refresh:'Refresh index',manage:'Manage folders',sources:'Image sources',directories:'Folders',addAnother:'+ Add another folder',permissionTip:'You may need to grant folder access again after reopening the browser.',drop:'Drop to add folder',privacy:'Your images stay on this device',empty:'No image folders added',reconnect:'Reconnect this gallery’s folders',select:'Choose folder',reconnectButton:'Reconnect folders',needReconnect:'Folders need reconnecting',none:'No images added',imageCount:(d,i)=>`${d} folders · ${i} images`,permission:'Permission required',photoCount:n=>`${n} images`,reconnectShort:'Reconnect',emptyDirectories:'No folders linked yet.'}};
const state = { locale:localStorage.getItem('locale')||'zh',galleries:[], activeGallery:localStorage.getItem('activeGallery')||'default', directories: [], images: [], shuffled: [], visible: 0, activeIndex: 0, urls: new Set(), loading: false, renderPending: false, lightboxUrl: null, renderVersion: 0, previewQueue: [], previewWorkers: 0, favorites:new Set(JSON.parse(localStorage.getItem('favorites')||'[]')), favoritesOnly:false, zoom:1 };
const t=key=>messages[state.locale][key];
const thumbnailWorker='Worker'in window&&'OffscreenCanvas'in window?new Worker('./thumbnail-worker.js'):null;
const workerJobs=new Map();let workerId=0;
if(thumbnailWorker)thumbnailWorker.onmessage=({data})=>{const job=workerJobs.get(data.id);if(!job)return;workerJobs.delete(data.id);data.error?job.reject(new Error(data.error)):job.resolve(data);};
const $ = (selector) => document.querySelector(selector);
const elements = { view:$('#galleryView'), galleryEmpty:$('#galleryEmpty'), gallery:$('#gallery'), count:$('#imageCount'), shuffle:$('#shuffleButton'), dialog:$('#directoryDialog'), list:$('#directoryList'), lightbox:$('#lightbox'), lightboxImage:$('#lightboxImage'), lightboxCaption:$('#lightboxCaption'), loading:$('#loading'), toast:$('#toast') };

function toast(message) { elements.toast.textContent=message; elements.toast.classList.add('show'); clearTimeout(toast.timer); toast.timer=setTimeout(()=>elements.toast.classList.remove('show'),2400); }
function shuffle(items) { const copy=[...items]; for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]];} return copy; }
function openDb() { return new Promise((resolve,reject)=>{ const request=indexedDB.open('shiguang-db',3); request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains('sources'))db.createObjectStore('sources',{keyPath:'id'});if(!db.objectStoreNames.contains('thumbnails'))db.createObjectStore('thumbnails');if(!db.objectStoreNames.contains('galleries'))db.createObjectStore('galleries',{keyPath:'id'});}; request.onsuccess=()=>resolve(request.result); request.onerror=()=>reject(request.error); }); }
async function storeRequest(store,mode,action){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(store,mode);const req=action(tx.objectStore(store));req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}
async function savedDirectories(galleryId=state.activeGallery) { try { let current=await storeRequest('sources','readonly',s=>s.getAll());if(!current.length){const db=await openDb();if(db.objectStoreNames.contains('directories')){const legacy=await storeRequest('directories','readonly',s=>s.getAll());current=legacy.map(item=>({...item,id:crypto.randomUUID(),galleryId:'default',enabled:true}));await Promise.all(current.map(saveDirectory));}}const missing=current.filter(item=>!item.galleryId);if(missing.length)await Promise.all(missing.map(item=>saveDirectory({...item,galleryId:'default'})));return current.map(item=>item.galleryId?item:{...item,galleryId:'default'}).filter(item=>item.galleryId===galleryId); } catch { return []; } }
async function saveDirectory(item) { return storeRequest('sources','readwrite',s=>s.put(item)); }
async function forgetDirectory(id) { return storeRequest('sources','readwrite',s=>s.delete(id)); }
async function loadGalleries(){let galleries=await storeRequest('galleries','readonly',s=>s.getAll());if(!galleries.length){galleries=[{id:'default',name:'默认图库',createdAt:Date.now()}];await storeRequest('galleries','readwrite',s=>s.put(galleries[0]));}return galleries;}
async function saveGallery(item){return storeRequest('galleries','readwrite',s=>s.put(item));}
async function getThumbnail(key){try{return await storeRequest('thumbnails','readonly',s=>s.get(key));}catch{return null}}
async function putThumbnail(key,value){try{await storeRequest('thumbnails','readwrite',s=>s.put({...value,usedAt:Date.now()},key));if(Math.random()<.04)trimThumbnailCache();}catch{}}
async function trimThumbnailCache(){try{const db=await openDb();const tx=db.transaction('thumbnails','readwrite'),store=tx.objectStore('thumbnails'),all=await new Promise((resolve,reject)=>{const request=store.getAll();request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)}),keys=await new Promise((resolve,reject)=>{const request=store.getAllKeys();request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});if(all.length>CACHE_LIMIT)all.map((value,index)=>({value,key:keys[index]})).sort((a,b)=>a.value.usedAt-b.value.usedAt).slice(0,all.length-CACHE_LIMIT).forEach(item=>store.delete(item.key));}catch{}}
function workerThumbnail(file){return new Promise((resolve,reject)=>{const id=++workerId;workerJobs.set(id,{resolve,reject});thumbnailWorker.postMessage({id,file,width:THUMBNAIL_WIDTH});});}

async function scanDirectory(handle, rootName=handle.name, rootId='', path='') {
  const found=[],queue=[{handle,path}];
  while(queue.length){const batch=queue.splice(0,6);const next=await Promise.all(batch.map(async node=>{const dirs=[];for await(const [name,entry] of node.handle.entries()){if(entry.kind==='directory')dirs.push({handle:entry,path:`${node.path}${name}/`});else if(IMAGE_TYPES.has(name.split('.').pop().toLowerCase())){found.push({name,path:`${rootName}/${node.path}${name}`,key:`${rootId}:${node.path}${name}`,handle:entry,directory:rootName});if(found.length%100===0)elements.count.textContent=`正在索引 · 已发现 ${found.length} 张图片`;}}return dirs;}));next.forEach(dirs=>queue.push(...dirs));}
  return found;
}
async function addDirectory() {
  if(!window.showDirectoryPicker){toast('当前浏览器不支持目录访问，请使用 Chrome 或 Edge');return;}
  try { const handle=await window.showDirectoryPicker({mode:'read'}); const item={id:crypto.randomUUID(),galleryId:state.activeGallery,name:handle.name,handle,count:0,enabled:true}; await saveDirectory(item); state.directories.push(item); await loadAll(); }
  catch(error){ if(error.name!=='AbortError') toast('无法读取该目录，请重试'); }
}
async function loadAll() {
  state.loading=true; elements.loading.hidden=false; renderShell(); revokeUrls(); const images=[];
  const results=await Promise.all(state.directories.map(async directory=>{ if(directory.enabled===false)return[];try {const permission=await directory.handle.queryPermission({mode:'read'});if(permission==='granted'){const found=directory.images??await scanDirectory(directory.handle,directory.name,directory.id);directory.images=found;directory.count=found.length;return found;}directory.count=null;}catch{directory.count=null;}return[];}));
  results.forEach(found=>images.push(...found));
  state.images=images; state.shuffled=shuffle(images); state.visible=0; state.loading=false; elements.loading.hidden=true; renderShell(); renderMore(); renderDirectories();
}
function revokeUrls(){state.renderVersion++;state.renderPending=false;state.previewQueue.length=0;state.urls.forEach(URL.revokeObjectURL);state.urls.clear();elements.gallery.innerHTML='';}
function applyLocale(){document.documentElement.lang=state.locale==='zh'?'zh-CN':'en';document.title=t('title');document.querySelectorAll('[data-i18n]').forEach(node=>node.textContent=t(node.dataset.i18n));$('#languageButton').textContent=state.locale==='zh'?'EN':'中';$('#newGalleryButton').innerHTML=`<span>＋</span>${t('newGallery')}`;renderGalleryPicker();renderShell();renderDirectories();}
function renderShell(){const has=state.directories.length>0,hasImages=state.images.length>0;elements.view.hidden=false;elements.galleryEmpty.hidden=state.loading||hasImages;$('#galleryEmptyText').textContent=has?t('reconnect'):t('empty');$('#galleryAddButton').textContent=has?t('reconnectButton'):t('select');elements.shuffle.disabled=!hasImages;$('#favoriteFilter').disabled=!hasImages;elements.count.textContent=hasImages?t('imageCount')(state.directories.length,state.images.length):has?t('needReconnect'):t('none');}
async function reconnectDirectories(){const pending=state.directories.filter(directory=>directory.enabled!==false);if(!pending.length)return;const permissions=await Promise.all(pending.map(directory=>directory.handle.requestPermission({mode:'read'}).catch(()=> 'denied')));pending.forEach((directory,index)=>{if(permissions[index]==='granted')directory.images=null;});if(permissions.some(permission=>permission==='granted'))await loadAll();else toast('未获得目录读取权限');}
function galleryName(gallery){return gallery.id==='default'?t('defaultGallery'):gallery.name}function renderGalleryPicker(){const active=state.galleries.find(gallery=>gallery.id===state.activeGallery);$('#currentGalleryName').textContent=active?galleryName(active):t('defaultGallery');$('#galleryOptions').innerHTML=state.galleries.map(gallery=>`<button class="gallery-option ${gallery.id===state.activeGallery?'active':''}" type="button" role="menuitem" data-gallery-id="${gallery.id}"><span>${escapeHtml(galleryName(gallery))}</span>${gallery.id===state.activeGallery?'<span class="check">✓</span>':''}</button>`).join('');$('#galleryOptions').querySelectorAll('.gallery-option').forEach(button=>button.onclick=()=>{closeGalleryMenu();switchGallery(button.dataset.galleryId);});}
function closeGalleryMenu(){const menu=$('#galleryMenu');menu.hidden=true;$('#galleryMenuButton').setAttribute('aria-expanded','false');}
async function switchGallery(id){sessionStorage.setItem(`galleryScroll:${state.activeGallery}`,String(scrollY));state.activeGallery=id;localStorage.setItem('activeGallery',id);state.directories=await savedDirectories(id);state.favoritesOnly=false;$('#favoriteFilter').classList.remove('active');await loadAll();renderGalleryPicker();requestAnimationFrame(()=>scrollTo(0,Number(sessionStorage.getItem(`galleryScroll:${id}`)||0)));}
function renderMore(){
  if(state.loading||state.renderPending||state.visible>=state.shuffled.length){elements.loading.hidden=state.visible>=state.shuffled.length&&!state.loading;return;}
  state.renderPending=true;
  const scheduledVersion=state.renderVersion;
  const run=()=>{if(scheduledVersion!==state.renderVersion){state.renderPending=false;return;}const end=Math.min(state.visible+BATCH_SIZE,state.shuffled.length);const version=state.renderVersion;const columns=ensureGalleryColumns();const tasks=[];for(let i=state.visible;i<end;i++){const image=state.shuffled[i];const button=document.createElement('button');button.className='photo-card';button.type='button';button.dataset.index=i;button.dataset.estimatedHeight='160';button.setAttribute('aria-label',`查看 ${image.name}`);button.innerHTML=`<span class="image-shell"><img alt="${escapeHtml(image.name)}" decoding="async"><span class="load-mark" aria-hidden="true"></span></span><span class="photo-meta">${escapeHtml(image.name)}</span>`;button.addEventListener('click',()=>openLightbox(i));const shortest=columns.reduce((best,column)=>Number(column.dataset.height||0)<Number(best.dataset.height||0)?column:best,columns[0]);shortest.appendChild(button);shortest.dataset.height=String(Number(shortest.dataset.height||0)+160);tasks.push({image,button,version});}tasks.forEach(queuePreview);state.visible=end;state.renderPending=false;};
  const finish=()=>{run();if(scheduledVersion!==state.renderVersion)return;elements.loading.hidden=state.visible>=state.shuffled.length;requestAnimationFrame(()=>{if(shouldLoadMore())renderMore();});};
  if('requestIdleCallback' in window) requestIdleCallback(finish,{timeout:250}); else requestAnimationFrame(finish);
}
function galleryColumnCount(){const width=innerWidth;return width<=680?2:width<=980?3:width<=1300?4:5;}
function shouldLoadMore(){if(state.loading||state.renderPending||state.visible>=state.shuffled.length)return false;const columns=[...elements.gallery.querySelectorAll('.gallery-column')];if(!columns.length)return true;const shortestBottom=Math.min(...columns.map(column=>column.getBoundingClientRect().bottom));return shortestBottom<innerHeight+1400;}
function ensureGalleryColumns(){let columns=[...elements.gallery.querySelectorAll('.gallery-column')];const count=galleryColumnCount();if(columns.length===count)return columns;if(columns.length){const cards=[...elements.gallery.querySelectorAll('.photo-card')];elements.gallery.innerHTML='';columns=[];for(let i=0;i<count;i++){const column=document.createElement('div');column.className='gallery-column';column.dataset.height='0';elements.gallery.appendChild(column);columns.push(column);}cards.forEach((card,index)=>{const column=columns[index%count];column.appendChild(card);column.dataset.height=String(Number(column.dataset.height)+Number(card.dataset.estimatedHeight||160));});return columns;}for(let i=0;i<count;i++){const column=document.createElement('div');column.className='gallery-column';column.dataset.height='0';elements.gallery.appendChild(column);columns.push(column);}return columns;}
function queuePreview(task){state.previewQueue.push(task);runPreviewQueue();}
function runPreviewQueue(){while(state.previewWorkers<THUMBNAIL_CONCURRENCY&&state.previewQueue.length){const task=state.previewQueue.shift();state.previewWorkers++;loadPreview(task).finally(()=>{state.previewWorkers--;runPreviewQueue();});}}
async function loadPreview({image,button,version}){
  if(version!==state.renderVersion||!button.isConnected)return;
  const file=await image.handle.getFile();let blob=file;
  let width=0,height=0;
  const extension=image.name.split('.').pop().toLowerCase();
  try {
    if(!['gif','svg'].includes(extension)&&'createImageBitmap' in window){
      const cacheKey=`${image.key}:${file.size}:${file.lastModified}`;const cached=await getThumbnail(cacheKey);if(cached){if(cached instanceof Blob)blob=cached;else{blob=cached.blob;width=cached.width;height=cached.height;}}else if(thumbnailWorker){const result=await workerThumbnail(file);blob=result.blob;width=result.width;height=result.height;putThumbnail(cacheKey,{blob,width,height});}else{const bitmap=await createImageBitmap(file,{resizeWidth:THUMBNAIL_WIDTH,resizeQuality:'high',imageOrientation:'from-image'});width=bitmap.width;height=bitmap.height;const canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;canvas.getContext('2d').drawImage(bitmap,0,0);bitmap.close();blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/webp',.82));canvas.width=canvas.height=1;putThumbnail(cacheKey,{blob,width,height});}
    }
  } catch { blob=file; }
  if(version!==state.renderVersion||!button.isConnected)return;
  const shell=button.querySelector('.image-shell');
  if(width&&height){shell.style.aspectRatio=`${width} / ${height}`;const column=button.parentElement;const estimated=Math.max(80,(button.clientWidth||THUMBNAIL_WIDTH)*height/width);column.dataset.height=String(Number(column.dataset.height||0)-Number(button.dataset.estimatedHeight||160)+estimated);button.dataset.estimatedHeight=String(estimated);}
  const url=URL.createObjectURL(blob||image.file);state.urls.add(url);
  const img=button.querySelector('img');
  img.addEventListener('load',()=>button.classList.add('is-loaded'),{once:true});
  img.addEventListener('error',()=>{state.urls.delete(url);URL.revokeObjectURL(url);button.remove();},{once:true});
  img.src=url;
}
function renderDirectories(){elements.list.innerHTML='';if(!state.directories.length){elements.list.innerHTML=`<p class="directory-detail">${t('emptyDirectories')}</p>`;return;}state.directories.forEach(directory=>{const row=document.createElement('div');row.className='directory-row';row.innerHTML=`<span class="folder-icon">▰</span><div><div class="directory-name">${escapeHtml(directory.name)}</div><div class="directory-detail">${directory.count===null?t('permission'):t('photoCount')(directory.count??0)}</div></div>${directory.count===null?`<button class="reconnect-button">${t('reconnectShort')}</button>`:`<button class="toggle-button ${directory.enabled===false?'off':''}" aria-label="Toggle">●</button>`}<button class="remove-button" aria-label="Remove ${escapeHtml(directory.name)}">×</button>`;const reconnect=row.querySelector('.reconnect-button');if(reconnect)reconnect.onclick=async()=>{if(await directory.handle.requestPermission({mode:'read'})==='granted'){directory.images=null;await loadAll();}};const toggle=row.querySelector('.toggle-button');if(toggle)toggle.onclick=async()=>{directory.enabled=directory.enabled===false;await saveDirectory({...directory,images:undefined});await loadAll();};row.querySelector('.remove-button').onclick=async()=>{await forgetDirectory(directory.id);state.directories=state.directories.filter(d=>d.id!==directory.id);await loadAll();};elements.list.appendChild(row);});}
function reshuffle(scroll=true){const source=state.favoritesOnly?state.images.filter(image=>state.favorites.has(image.key)):state.images;state.shuffled=shuffle(source);state.visible=0;revokeUrls();renderMore();if(scroll)window.scrollTo({top:0,behavior:'smooth'});if(state.favoritesOnly&&!source.length)toast('还没有收藏图片');else if(scroll)toast('已经换了一批');}
async function openLightbox(index){state.activeIndex=index;const item=state.shuffled[index];const file=await item.handle.getFile();if(state.lightboxUrl)URL.revokeObjectURL(state.lightboxUrl);state.lightboxUrl=URL.createObjectURL(file);elements.lightboxImage.src=state.lightboxUrl;elements.lightboxImage.alt=item.name;elements.lightboxCaption.textContent=`${item.path} · ${Math.round(file.size/1024)} KB · ${new Date(file.lastModified).toLocaleDateString()}`;state.zoom=1;elements.lightboxImage.style.setProperty('--zoom',1);$('#favoriteImage').classList.toggle('active',state.favorites.has(item.key));if(!elements.lightbox.open)elements.lightbox.showModal();}
function moveLightbox(step){if(!state.shuffled.length)return;openLightbox((state.activeIndex+step+state.shuffled.length)%state.shuffled.length);}
function escapeHtml(value){return value.replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));}

$('#addButton').onclick=$('#dialogAddButton').onclick=addDirectory;
$('#galleryAddButton').onclick=()=>state.directories.length?reconnectDirectories():addDirectory();
$('#manageButton').onclick=()=>elements.dialog.showModal();
$('#languageButton').onclick=()=>{state.locale=state.locale==='zh'?'en':'zh';localStorage.setItem('locale',state.locale);applyLocale();};
$('#galleryMenuButton').onclick=event=>{event.stopPropagation();const menu=$('#galleryMenu');menu.hidden=!menu.hidden;$('#galleryMenuButton').setAttribute('aria-expanded',String(!menu.hidden));};
$('#newGalleryButton').onclick=async()=>{closeGalleryMenu();const name=prompt('新图库名称');if(!name?.trim())return;const gallery={id:crypto.randomUUID(),name:name.trim().slice(0,40),createdAt:Date.now()};await saveGallery(gallery);state.galleries.push(gallery);renderGalleryPicker();await switchGallery(gallery.id);toast(`已创建“${gallery.name}”`);};
document.addEventListener('click',event=>{if(!event.target.closest('.gallery-switcher'))closeGalleryMenu();});
document.addEventListener('keydown',event=>{if(event.key==='Escape')closeGalleryMenu();});
elements.shuffle.onclick=reshuffle;
$('#favoriteFilter').onclick=()=>{state.favoritesOnly=!state.favoritesOnly;$('#favoriteFilter').classList.toggle('active',state.favoritesOnly);reshuffle();};
$('#favoriteImage').onclick=()=>{const key=state.shuffled[state.activeIndex]?.key;if(!key)return;if(state.favorites.has(key))state.favorites.delete(key);else state.favorites.add(key);localStorage.setItem('favorites',JSON.stringify([...state.favorites]));$('#favoriteImage').classList.toggle('active',state.favorites.has(key));};
$('#refreshButton').onclick=async()=>{state.directories.forEach(directory=>directory.images=null);await loadAll();toast('目录索引已刷新');};
$('#zoomIn').onclick=()=>{state.zoom=Math.min(4,state.zoom+.25);elements.lightboxImage.style.setProperty('--zoom',state.zoom)};
$('#zoomOut').onclick=()=>{state.zoom=Math.max(.5,state.zoom-.25);elements.lightboxImage.style.setProperty('--zoom',state.zoom)};
$('#fullscreenImage').onclick=()=>document.fullscreenElement?document.exitFullscreen():elements.lightbox.requestFullscreen();
$('#previousImage').onclick=()=>moveLightbox(-1); $('#nextImage').onclick=()=>moveLightbox(1);
document.querySelectorAll('[data-close]').forEach(button=>button.onclick=()=>document.getElementById(button.dataset.close).close());
elements.lightbox.addEventListener('click',event=>{if(event.target===elements.lightbox||event.target===elements.lightbox.querySelector('figure'))elements.lightbox.close();});
elements.dialog.addEventListener('click',event=>{if(event.target===elements.dialog)elements.dialog.close();});
document.addEventListener('keydown',event=>{if(!elements.lightbox.open)return;if(event.key==='ArrowLeft')moveLightbox(-1);if(event.key==='ArrowRight')moveLightbox(1);});
const loadObserver=new IntersectionObserver(entries=>{if(entries[0].isIntersecting)renderMore();},{rootMargin:'1200px 0px'});
loadObserver.observe(elements.loading);
elements.lightbox.addEventListener('close',()=>{if(state.lightboxUrl)URL.revokeObjectURL(state.lightboxUrl);state.lightboxUrl=null;elements.lightboxImage.removeAttribute('src');});
elements.lightbox.addEventListener('wheel',event=>{event.preventDefault();state.zoom=Math.max(.5,Math.min(4,state.zoom+(event.deltaY<0?.15:-.15)));elements.lightboxImage.style.setProperty('--zoom',state.zoom)},{passive:false});
elements.lightboxImage.addEventListener('dblclick',()=>{state.zoom=state.zoom===1?2:1;elements.lightboxImage.style.setProperty('--zoom',state.zoom)});
window.addEventListener('beforeunload',revokeUrls);
let dragDepth=0;window.addEventListener('dragenter',event=>{event.preventDefault();dragDepth++;document.body.classList.add('dragging')});window.addEventListener('dragover',event=>event.preventDefault());window.addEventListener('dragleave',()=>{if(--dragDepth<=0){dragDepth=0;document.body.classList.remove('dragging')}});window.addEventListener('drop',async event=>{event.preventDefault();dragDepth=0;document.body.classList.remove('dragging');const handles=await Promise.all([...event.dataTransfer.items].map(item=>item.getAsFileSystemHandle?.()));for(const handle of handles){if(handle?.kind==='directory'){const item={id:crypto.randomUUID(),galleryId:state.activeGallery,name:handle.name,handle,count:0,enabled:true};await saveDirectory(item);state.directories.push(item);}}if(handles.some(handle=>handle?.kind==='directory'))await loadAll();else toast('请拖入一个目录');});
let scrollTimer,loadFrame;window.addEventListener('scroll',()=>{clearTimeout(scrollTimer);scrollTimer=setTimeout(()=>sessionStorage.setItem(`galleryScroll:${state.activeGallery}`,String(scrollY)),150);if(!loadFrame)loadFrame=requestAnimationFrame(()=>{loadFrame=0;if(shouldLoadMore())renderMore();});},{passive:true});
let resizeTimer;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(ensureGalleryColumns,160)});

(async function init(){state.galleries=await loadGalleries();if(!state.galleries.some(gallery=>gallery.id===state.activeGallery))state.activeGallery=state.galleries[0].id;state.directories=await savedDirectories();applyLocale();if(state.directories.length)await loadAll();const savedScroll=Number(sessionStorage.getItem(`galleryScroll:${state.activeGallery}`)||0);if(savedScroll)requestAnimationFrame(()=>scrollTo(0,savedScroll));})();

if(location.hostname==='127.0.0.1'&&'serviceWorker'in navigator)window.addEventListener('load',async()=>{const registration=await navigator.serviceWorker.getRegistration('./');await registration?.unregister();if('caches'in window)await caches.delete('picviewer-shell-v1');});
